language: go

go:
  - 1.13.x
  - 1.14.x
  - tip

services:
  - mysql

before_install:
  - mysql -u root --password="" < travis.sql
  - go get -t -v ./...

script:
  - go test ./... -timeout 60s -race -coverprofile=coverage.txt -covermode=atomic

before_script:
  - mv .env.travis .env
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
