language: go

go:
  - 1.12.x
  - tip

services:
  - mysql

before_install:
  - mysql -u root --password="" < travis.sql
  - go get -t -v ./...

script:
  - go test ./...

before_script:
  - mv .env.travis .env.test
  - go vet ./...
